# Generated by Django 5.2.16 on 2026-08-09 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'أعزب'), ('MARRIED', 'متزوج'), ('DIVORCED', 'مطلق'), ('WIDOWED', 'أرمل')], max_length=20)),
                ('children_count', models.PositiveSmallIntegerField(default=0)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wilaya', models.CharField(max_length=120)),
                ('residence', models.CharField(max_length=180)),
                ('requested_position', models.CharField(choices=[('SELLER', 'بائع'), ('DRIVER', 'سائق'), ('DRIVER_SELLER', 'سائق وبائع'), ('WAREHOUSE_KEEPER', 'أمين مخزن'), ('ACCOUNTING_MANAGER', 'مدير حسابات'), ('SALES_MANAGER', 'مسير مبيعات'), ('SALES_SUPERVISOR', 'مشرف مبيعات')], max_length=32)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('previous_companies', models.TextField(blank=True)),
                ('has_driving_license', models.BooleanField(default=False)),
                ('driving_license_category', models.CharField(blank=True, max_length=50)),
                ('driving_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, upload_to='recruitment/cv/%Y/%m/')),
                ('status', models.CharField(choices=[('NEW', 'جديد'), ('REVIEWING', 'قيد المراجعة'), ('CONTACTED', 'تم التواصل'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='NEW', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='recruit_status_sub_idx'), models.Index(fields=['requested_position', '-submitted_at'], name='recruit_position_sub_idx')],
            },
        ),
    ]
