# Generated by Django 5.2.16 on 2026-07-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, help_text='رقم اختياري وفريد للعامل داخل الشركة.', max_length=30, null=True, unique=True, verbose_name='الرقم الداخلي')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('last_name', models.CharField(max_length=100, verbose_name='اللقب')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='ألغِ التحديد لتعطيل العامل دون حذف سجله.', verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'عامل',
                'verbose_name_plural': 'العمال',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='worker_name_idx')],
            },
        ),
    ]
