# Generated by Django 5.2.16 on 2026-07-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_worker_code_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='رمز ثابت يستعمله النظام ولا يتغير.', max_length=40, null=True, unique=True, verbose_name='الرمز التقني')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('default_can_drive', models.BooleanField(default=False, verbose_name='القيادة افتراضيًا')),
                ('default_can_sell', models.BooleanField(default=False, verbose_name='البيع افتراضيًا')),
                ('default_can_work_in_warehouse', models.BooleanField(default=False, verbose_name='العمل في المخزن افتراضيًا')),
                ('default_can_assist_distribution', models.BooleanField(default=False, verbose_name='مساعدة التوزيع افتراضيًا')),
                ('default_can_train_workers', models.BooleanField(default=False, verbose_name='تدريب العمال افتراضيًا')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='عطّل الصنف بدل حذفه للحفاظ على التاريخ.', verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='صنف أساسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_categories_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_categories_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
            ],
            options={
                'verbose_name': 'صنف عامل',
                'verbose_name_plural': 'أصناف العمال',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='worker_category_state_idx')],
            },
        ),
    ]
