# Generated by Django 5.2.16 on 2026-07-24 17:32

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_seed_worker_categories'),
        ('fleet', '0003_enable_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPositionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاريخ بداية المنصب')),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='اتركه فارغًا إذا كان العامل ما زال في هذا المنصب.', null=True, verbose_name='تاريخ نهاية المنصب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_position_periods', to='workforce.workercategory', verbose_name='صنف المنصب')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_position_periods_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_position_periods_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدله')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_periods', to='workforce.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'فترة منصب عامل',
                'verbose_name_plural': 'تاريخ مناصب العمال',
                'ordering': ('-start_date', 'worker', 'category'),
                'indexes': [models.Index(fields=['worker', 'start_date'], name='worker_position_start_idx'), models.Index(fields=['category', 'start_date'], name='position_category_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='worker_position_end_after_start', violation_error_message='تاريخ نهاية المنصب لا يمكن أن يكون قبل تاريخ البداية.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(models.Func('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True), function='DATERANGE', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&'), ('worker', '=')], name='exclude_overlapping_worker_positions', violation_error_message='هذا العامل مرتبط بمنصب آخر خلال جزء من هذه الفترة.')],
            },
        ),
    ]
