# Generated by Django 5.2.16 on 2026-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_workerpositionperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='can_assist_distribution',
            field=models.BooleanField(default=False, help_text='العامل مؤهل لمساعدة طاقم التوزيع.', verbose_name='يستطيع مساعدة التوزيع'),
        ),
        migrations.AddField(
            model_name='worker',
            name='can_drive',
            field=models.BooleanField(default=False, help_text='العامل مؤهل لقيادة شاحنات التوزيع.', verbose_name='يستطيع القيادة'),
        ),
        migrations.AddField(
            model_name='worker',
            name='can_sell',
            field=models.BooleanField(default=False, help_text='العامل مؤهل للبيع والتعامل مع الزبائن.', verbose_name='يستطيع البيع'),
        ),
        migrations.AddField(
            model_name='worker',
            name='can_train_workers',
            field=models.BooleanField(default=False, help_text='العامل مؤهل لمرافقة وتدريب عمال آخرين.', verbose_name='يستطيع تدريب العمال'),
        ),
        migrations.AddField(
            model_name='worker',
            name='can_work_in_warehouse',
            field=models.BooleanField(default=False, help_text='العامل مؤهل لمهام المخزن.', verbose_name='يستطيع العمل في المخزن'),
        ),
    ]
