# Generated by Django 5.2.16 on 2026-07-24 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_worker_can_assist_distribution_worker_can_drive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='رمز ثابت تستعمله المنظومة ولا يتغير بعد إنشاء القدرة.', max_length=40, null=True, unique=True, verbose_name='الرمز التقني')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القدرة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='الرقم الأصغر يظهر أولًا.', verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='عطّل القدرة بدل حذفها للحفاظ على ارتباطاتها.', verbose_name='نشطة')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='قدرة أساسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_capabilities_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_capabilities_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر من عدلها')),
            ],
            options={
                'verbose_name': 'قدرة عامل',
                'verbose_name_plural': 'قدرات العمال',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='capabilities',
            field=models.ManyToManyField(blank=True, help_text='القدرات الفعلية الخاصة بالعامل، وهي مستقلة عن منصبه الرسمي.', related_name='workers', to='workforce.workercapability', verbose_name='قدرات العامل'),
        ),
        migrations.AddField(
            model_name='workercategory',
            name='default_capabilities',
            field=models.ManyToManyField(blank=True, help_text='قدرات مقترحة لهذا الصنف، ولا تغيّر قدرات العامل تلقائيًا.', related_name='default_for_categories', to='workforce.workercapability', verbose_name='القدرات الافتراضية'),
        ),
        migrations.AddIndex(
            model_name='workercapability',
            index=models.Index(fields=['is_active', 'sort_order'], name='worker_capability_state_idx'),
        ),
    ]
