# Generated by Django 5.2.16 on 2026-07-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_seed_and_migrate_worker_capabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='can_assist_distribution',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='can_drive',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='can_sell',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='can_train_workers',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='can_work_in_warehouse',
        ),
        migrations.RemoveField(
            model_name='workercategory',
            name='default_can_assist_distribution',
        ),
        migrations.RemoveField(
            model_name='workercategory',
            name='default_can_drive',
        ),
        migrations.RemoveField(
            model_name='workercategory',
            name='default_can_sell',
        ),
        migrations.RemoveField(
            model_name='workercategory',
            name='default_can_train_workers',
        ),
        migrations.RemoveField(
            model_name='workercategory',
            name='default_can_work_in_warehouse',
        ),
    ]
