# Generated by Django 5.2.16 on 2026-08-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskDeliskyAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('brand_id_value', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('INVALID_REQUEST', 'Invalid request'), ('RATE_LIMITED', 'Rate limited'), ('RATE_LIMIT_CONFIGURATION_ERROR', 'Rate-limit configuration error'), ('PROVIDER_CONFIGURATION_ERROR', 'Provider configuration error'), ('PROVIDER_DISABLED', 'Provider disabled'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable')], db_index=True, max_length=40)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
