# Generated by Django 5.2.16 on 2026-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_askdeliskyauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='askdeliskyauditevent',
            name='scope',
            field=models.CharField(choices=[('manager_ask', 'Ask DELISKY'), ('marketing_helper', 'Marketing helper')], db_index=True, default='manager_ask', max_length=32),
        ),
    ]
