# Generated by Django 5.2.16 on 2026-07-16 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, help_text='رمز اختياري وفريد للشاحنة داخل الشركة.', max_length=30, null=True, unique=True, verbose_name='الرمز الداخلي')),
                ('registration_number', models.CharField(help_text='رقم تسجيل الشاحنة كما هو موجود في الوثائق.', max_length=50, unique=True, verbose_name='رقم التسجيل')),
                ('brand', models.CharField(max_length=100, verbose_name='العلامة')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='الطراز')),
                ('manufacturing_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='سنة الصنع')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='ألغِ التحديد لتعطيل الشاحنة دون حذف تاريخها.', verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'شاحنة',
                'verbose_name_plural': 'الشاحنات',
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['brand', 'model'], name='truck_brand_model_idx')],
            },
        ),
    ]
