# Generated by Django 5.2.16 on 2026-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturing_year__isnull', True), models.Q(('manufacturing_year__gte', 1900), ('manufacturing_year__lte', 2100)), _connector='OR'), name='truck_year_1900_2100'),
        ),
    ]
