# Generated by Django 5.2.16 on 2026-07-16 17:59

import apps.fleet.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_enable_btree_gist'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTruckAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاريخ بداية العمل')),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='اتركه فارغًا إذا كان العامل ما زال يعمل مع الشاحنة.', null=True, verbose_name='تاريخ نهاية العمل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_assignments', to='fleet.truck', verbose_name='الشاحنة')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_assignments', to='workforce.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'تعيين عامل بشاحنة',
                'verbose_name_plural': 'تعيينات العمال بالشاحنات',
                'ordering': ['-start_date', 'truck', 'worker'],
                'indexes': [models.Index(fields=['truck', 'start_date'], name='assignment_truck_start_idx'), models.Index(fields=['worker', 'start_date'], name='assignment_worker_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='assignment_end_not_before_start', violation_error_message='تاريخ نهاية العمل لا يمكن أن يكون قبل تاريخ البداية.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(apps.fleet.models.DateRangeExpression('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('truck', '=')], name='exclude_overlapping_truck_assignments', violation_error_message='هذه الشاحنة مرتبطة بعامل آخر خلال جزء من هذه الفترة.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(apps.fleet.models.DateRangeExpression('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('worker', '=')], name='exclude_overlapping_worker_assignments', violation_error_message='هذا العامل مرتبط بشاحنة أخرى خلال جزء من هذه الفترة.')],
            },
        ),
    ]
