# Generated by Django 5.2.16 on 2026-07-26 21:23

import apps.fleet.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_assignments(
    apps,
    schema_editor,
):
    WorkerTruckAssignment = apps.get_model(
        "fleet",
        "WorkerTruckAssignment",
    )
    TruckCrewAssignment = apps.get_model(
        "fleet",
        "TruckCrewAssignment",
    )

    for assignment in (
        WorkerTruckAssignment.objects
        .all()
        .iterator()
    ):
        TruckCrewAssignment.objects.create(
            worker_id=assignment.worker_id,
            truck_id=assignment.truck_id,
            crew_role="SELLER",
            is_primary_seller=True,
            start_date=assignment.start_date,
            end_date=assignment.end_date,
            notes=assignment.notes,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_add_distribution_truck_identity'),
        ('workforce', '0009_remove_legacy_capability_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_role', models.CharField(choices=[('SELLER', 'بائع'), ('DRIVER', 'سائق'), ('DISTRIBUTION_ASSISTANT', 'مساعد توزيع'), ('TRAINEE', 'متربص')], max_length=30, verbose_name='الدور داخل الطاقم')),
                ('is_primary_seller', models.BooleanField(default=False, help_text='تُنسب المبيعات والزيارات إلى البائع الرئيسي فقط.', verbose_name='البائع الرئيسي')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='اتركه فارغًا إذا كان العامل ما زال ضمن الطاقم.', null=True, verbose_name='تاريخ النهاية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_assignments', to='fleet.truck', verbose_name='شاحنة التوزيع')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_crew_assignments', to='workforce.worker', verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'عضو طاقم شاحنة توزيع',
                'verbose_name_plural': 'طواقم شاحنات التوزيع',
                'ordering': ['-start_date', 'truck', 'crew_role', 'worker'],
                'indexes': [models.Index(fields=['truck', 'start_date'], name='crew_truck_start_idx'), models.Index(fields=['worker', 'start_date'], name='crew_worker_start_idx'), models.Index(fields=['truck', 'is_primary_seller', 'start_date'], name='crew_primary_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='crew_end_not_before_start', violation_error_message='تاريخ النهاية لا يمكن أن يكون قبل تاريخ البداية.'), models.CheckConstraint(condition=models.Q(('is_primary_seller', False), ('crew_role__in', ['SELLER', 'DRIVER']), _connector='OR'), name='crew_valid_primary_seller_role', violation_error_message='المساعد والمتربص لا يمكن أن يكونا بائعًا رئيسيًا.'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(apps.fleet.models.DateRangeExpression('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('worker', '=')], name='exclude_overlapping_worker_crew', violation_error_message='هذا العامل موجود ضمن طاقم آخر خلال جزء من هذه الفترة.'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_primary_seller', True)), expressions=[(apps.fleet.models.DateRangeExpression('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('truck', '=')], name='exclude_overlapping_primary_sellers', violation_error_message='يوجد بائع رئيسي آخر لهذه الشاحنة خلال جزء من الفترة.')],
            },
        ),
        migrations.RunPython(
            copy_legacy_assignments,
            migrations.RunPython.noop,
        ),
    ]
