# Generated by Django 5.2.16 on 2026-07-18 13:33

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='رمز مختصر وفريد مثل BIFA أو NITA.', max_length=30, validators=[django.core.validators.RegexValidator(message='يجب أن يبدأ الرمز بحرف أو رقم، ويحتوي فقط على حروف إنجليزية كبيرة، أرقام، شرطة أو شرطة سفلية.', regex='^[A-Z0-9][A-Z0-9_-]*$')], verbose_name='رمز الصنف')),
                ('name', models.CharField(help_text='الاسم الذي يظهر للمستخدمين.', max_length=120, verbose_name='اسم الصنف')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='ألغِ التحديد لإيقاف الصنف دون حذف بياناته التاريخية.', verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'صنف تجاري',
                'verbose_name_plural': 'الأصناف التجارية',
                'ordering': ['name', 'code'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='dist_brand_name_ci_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='dist_brand_code_ci_uniq', violation_error_message='يوجد صنف آخر يستعمل نفس الرمز.')],
            },
        ),
    ]
