# Generated by Django 5.2.16 on 2026-07-18 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('OPENING_STOCK', 'المخزون الافتتاحي'), ('CHARGEMENT', 'التحميل'), ('SALES', 'المبيعات'), ('ITEMS', 'تفاصيل المنتجات'), ('POS', 'نقاط البيع والزيارات')], db_index=True, max_length=30, verbose_name='نوع الملف')),
                ('period_start', models.DateField(db_index=True, verbose_name='تاريخ البداية')),
                ('period_end', models.DateField(db_index=True, verbose_name='تاريخ النهاية')),
                ('opening_month', models.DateField(blank=True, db_index=True, editable=False, help_text='حقل تقني يحدد أول يوم من شهر المخزون الافتتاحي.', null=True, verbose_name='شهر المخزون الافتتاحي')),
                ('source_file', models.FileField(blank=True, help_text='يحفظ مؤقتًا ويحذف بعد نجاح الاعتماد.', upload_to='imports/pending/%Y/%m/', verbose_name='الملف المرفوع')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('worksheet_name', models.CharField(blank=True, max_length=255, verbose_name='اسم ورقة Excel')),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف بالبايت')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='يجب أن تتكون بصمة SHA-256 من 64 حرفًا سداسيًا.', regex='^[0-9a-fA-F]{64}$')], verbose_name='بصمة الملف SHA-256')),
                ('content_sha256', models.CharField(blank=True, db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='يجب أن تتكون بصمة SHA-256 من 64 حرفًا سداسيًا.', regex='^[0-9a-fA-F]{64}$')], verbose_name='بصمة المحتوى المنظف')),
                ('status', models.CharField(choices=[('PENDING', 'في انتظار المراجعة'), ('REVIEWED', 'تمت المراجعة'), ('BLOCKED', 'مرفوض بسبب أخطاء'), ('APPROVED', 'معتمد'), ('SUPERSEDED', 'مستبدل بدفعة أحدث'), ('FAILED', 'فشلت العملية')], db_index=True, default='PENDING', max_length=20, verbose_name='حالة الاستيراد')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('accepted_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف المقبولة')),
                ('excluded_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف المستبعدة')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحذيرات')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('review_summary', models.JSONField(blank=True, default=dict, verbose_name='ملخص المراجعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده المستخدم')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='imports.distributionbrand', verbose_name='الصنف التجاري')),
                ('replaces_batch', models.ForeignKey(blank=True, help_text='تحدد الدفعة القديمة عند اعتماد ملف مصحح.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_batches', to='imports.importbatch', verbose_name='يستبدل دفعة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='راجعه المستخدم')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='رفعه المستخدم')),
            ],
            options={
                'verbose_name': 'دفعة استيراد',
                'verbose_name_plural': 'دفعات الاستيراد',
                'ordering': ['-uploaded_at', '-id'],
                'indexes': [models.Index(fields=['brand', 'report_type', 'period_start'], name='import_brand_type_start_idx'), models.Index(fields=['status', 'uploaded_at'], name='import_status_uploaded_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='import_period_end_not_before_start', violation_error_message='تاريخ النهاية لا يمكن أن يكون قبل البداية.'), models.CheckConstraint(condition=models.Q(models.Q(('report_type', 'OPENING_STOCK'), _negated=True), ('period_end', models.F('period_start')), _connector='OR'), name='opening_stock_single_date', violation_error_message='يجب أن يكون المخزون الافتتاحي مرتبطًا بتاريخ واحد.'), models.UniqueConstraint(condition=models.Q(('opening_month__isnull', False), ('report_type', 'OPENING_STOCK'), ('status', 'APPROVED')), fields=('brand', 'opening_month'), name='import_approved_opening_month_uniq', violation_error_message='سبق اعتماد مخزون افتتاحي لهذا الصنف خلال نفس الشهر.'), models.UniqueConstraint(condition=models.Q(('replaces_batch__isnull', False), ('status__in', ['APPROVED', 'SUPERSEDED'])), fields=('replaces_batch',), name='import_replaced_batch_once_uniq', violation_error_message='سبق ربط هذه الدفعة بدفعة مصححة معتمدة.'), models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('file_sha256',), name='import_approved_file_sha_uniq', violation_error_message='سبق اعتماد نفس الملف.'), models.UniqueConstraint(condition=models.Q(('status', 'APPROVED'), models.Q(('content_sha256', ''), _negated=True)), fields=('brand', 'report_type', 'period_start', 'period_end', 'content_sha256'), name='import_approved_content_uniq', violation_error_message='سبق اعتماد نفس المحتوى لهذا الصنف والفترة.')],
            },
        ),
    ]
