# Generated by Django 5.2.16 on 2026-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='stopped_rows',
            field=models.PositiveIntegerField(default=0, help_text='صفوف تمثل شاحنات متوقفة ولا تدخل في حساب الفشل.', verbose_name='الصفوف المتوقفة'),
        ),
    ]
