# Generated by Django 5.2.16 on 2026-07-18 18:10

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importbatch_stopped_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row_number', models.PositiveIntegerField(verbose_name='رقم الصف في Excel')),
                ('status', models.CharField(choices=[('ACCEPTED', 'مقبول'), ('EXCLUDED', 'مستبعد'), ('STOPPED', 'مؤشر توقف')], db_index=True, max_length=20, verbose_name='حالة الصف')),
                ('raw_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='البيانات الأصلية')),
                ('cleaned_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='البيانات المنظفة')),
                ('issues', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='الأخطاء والتحذيرات')),
                ('row_sha256', models.CharField(db_index=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='يجب أن تتكون بصمة SHA-256 من 64 حرفًا سداسيًا.', regex='^[0-9a-fA-F]{64}$')], verbose_name='بصمة الصف SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch', verbose_name='دفعة الاستيراد')),
            ],
            options={
                'verbose_name': 'صف استيراد',
                'verbose_name_plural': 'صفوف الاستيراد',
                'ordering': ['batch_id', 'excel_row_number'],
                'indexes': [models.Index(fields=['batch', 'status'], name='import_row_batch_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'excel_row_number'), name='import_row_batch_excel_uniq', violation_error_message='لا يمكن حفظ نفس رقم صف Excel أكثر من مرة داخل نفس الدفعة.'), models.CheckConstraint(condition=models.Q(('excel_row_number__gte', 2)), name='import_row_excel_number_gte_2', violation_error_message='يجب أن يكون رقم صف Excel 2 أو أكثر.')],
            },
        ),
    ]
