# Generated by Django 5.2.16 on 2026-08-17 10:27

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_add_truck_crew_assignment'),
        ('imports', '0004_importrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='import_source_system_code_ci_uniq', violation_error_message='يوجد نظام مصدر آخر يستعمل نفس الرمز.')],
            },
        ),
        migrations.CreateModel(
            name='SourceTruckMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_mappings', to='imports.importsourcesystem')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_mappings', to='fleet.truck')),
            ],
            options={
                'ordering': ['source_system__code', 'source_code'],
                'constraints': [models.UniqueConstraint(models.F('source_system'), django.db.models.functions.text.Lower('source_code'), name='source_truck_map_source_code_ci_uniq', violation_error_message='يوجد ربط آخر لنفس كود الشاحنة داخل نظام المصدر نفسه.')],
            },
        ),
    ]
