# Generated by Django 5.2.16 on 2026-08-17 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_importsourcesystem_sourcetruckmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSourceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, upload_to='imports/raw/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('worksheet_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('file_sha256', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='يجب أن تتكون بصمة SHA-256 من 64 حرفًا سداسيًا.', regex='^[0-9a-fA-F]{64}$')])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='import_approved_file_sha_uniq',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='يجب أن تتكون بصمة SHA-256 من 64 حرفًا سداسيًا.', regex='^[0-9a-fA-F]{64}$')], verbose_name='بصمة الملف SHA-256'),
        ),
        migrations.AddField(
            model_name='importsourceupload',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_uploads', to='imports.importsourcesystem'),
        ),
        migrations.AddField(
            model_name='importsourceupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_import_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_batches', to='imports.importsourceupload'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_upload__isnull', True), models.Q(('file_sha256', ''), _negated=True)), models.Q(('source_upload__isnull', False), ('file_sha256', '')), _connector='OR'), name='import_batch_one_source_identity', violation_error_message='يجب أن تعتمد الدفعة على ملف مباشر أو ملف خام مشتق، وليس الاثنين معًا.'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('source_upload__isnull', False)), fields=('source_upload', 'brand', 'report_type', 'period_start', 'period_end'), name='import_source_scope_uniq', violation_error_message='سبق إنشاء دفعة مشتقة لنفس الملف والصنف والنوع والفترة.'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED'), models.Q(('file_sha256', ''), _negated=True)), fields=('file_sha256',), name='import_approved_file_sha_uniq', violation_error_message='سبق اعتماد نفس الملف.'),
        ),
        migrations.AddConstraint(
            model_name='importsourceupload',
            constraint=models.UniqueConstraint(fields=('file_sha256',), name='import_source_upload_file_sha_uniq', violation_error_message='سبق رفع نفس الملف الخام.'),
        ),
    ]
