# Generated by Django 5.2.16 on 2026-08-20 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_importsourceupload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='import_source_scope_uniq',
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('source_upload__isnull', False), ('status__in', ['PENDING', 'REVIEWED', 'BLOCKED', 'FAILED'])), fields=('source_upload', 'brand', 'report_type', 'period_start', 'period_end'), name='import_src_scope_mutable_uniq', violation_error_message='سبق إنشاء دفعة مشتقة قابلة للتعديل لنفس الملف والصنف والنوع والفترة.'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('source_upload__isnull', False), ('status', 'APPROVED')), fields=('source_upload', 'brand', 'report_type', 'period_start', 'period_end'), name='import_src_scope_approved_uniq', violation_error_message='سبق اعتماد دفعة مشتقة لنفس الملف والصنف والنوع والفترة.'),
        ),
    ]
