# Generated by Django 5.2.16 on 2026-08-24 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_remove_importbatch_import_source_scope_uniq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_code', models.CharField(blank=True, help_text='Product identifier from the source system, for example Num from the STOCK reference file.', max_length=120)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('designation', models.CharField(max_length=255)),
                ('normalized_designation', models.CharField(db_index=True, editable=False, max_length=255)),
                ('units_per_carton', models.PositiveIntegerField(blank=True, help_text='Number of source units that represent one carton. Null means the conversion factor is unknown.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('needs_review', models.BooleanField(db_index=True, default=True, help_text='Marks products whose packaging information must be confirmed by the accountant.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_product_packagings', to='imports.distributionbrand')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_packagings', to='imports.importsourcesystem')),
            ],
            options={
                'ordering': ['source_system__code', 'designation', 'id'],
                'indexes': [models.Index(fields=['source_system', 'normalized_designation'], name='src_prod_name_idx'), models.Index(fields=['source_system', 'barcode'], name='src_prod_barcode_idx'), models.Index(fields=['needs_review', 'is_active'], name='src_prod_review_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_product_code', ''), _negated=True), fields=('source_system', 'source_product_code'), name='src_product_code_uniq', violation_error_message='A product with the same source code already exists in this source system.'), models.CheckConstraint(condition=models.Q(('units_per_carton__isnull', True), ('units_per_carton__gte', 1), _connector='OR'), name='src_product_packaging_gte1', violation_error_message='units_per_carton must be at least 1 when it is known.')],
            },
        ),
    ]
