# Generated by Django 5.2.16 on 2026-08-27 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_sourceproductpackaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alternative or historical product designation used by the source system.', max_length=255)),
                ('normalized_alias', models.CharField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='imports.sourceproductpackaging')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_aliases', to='imports.importsourcesystem')),
            ],
            options={
                'ordering': ['source_system__code', 'normalized_alias', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'normalized_alias'), name='src_prod_alias_uniq', violation_error_message='The same product alias already exists in this source system.')],
            },
        ),
    ]
