# Generated by Django 5.2.16 on 2026-08-31 19:03

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_sourceproductalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsourceupload',
            name='audit_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SourceTruckExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=120)),
                ('reason', models.CharField(default='OUT_OF_SCOPE', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_exclusions', to='imports.importsourcesystem')),
            ],
            options={
                'ordering': ['source_system__code', 'source_code'],
                'constraints': [models.UniqueConstraint(models.F('source_system'), django.db.models.functions.text.Lower('source_code'), name='source_truck_exclusion_code_ci_uniq', violation_error_message='An exclusion already exists for this source code and source system.')],
            },
        ),
    ]
