# Generated by Django 5.2.16 on 2026-09-02 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0010_importsourceupload_audit_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='import_approved_opening_month_uniq',
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'OPENING_STOCK'), ('status', 'APPROVED')), fields=('brand', 'period_start'), name='import_approved_opening_date_uniq', violation_error_message='سبق اعتماد لقطة مخزون لهذا الصنف في نفس التاريخ.'),
        ),
    ]
